### PR TITLE
Updated tomcat version to 8.0.32

### PR DESCRIPTION
**Pull request by lukaszraczylo**

### CODE REVIEW

**Comment by skyguy94** [comment]
This is not the repo you are looking for. I only maintain the 7.0.59 package for the same problem you are having with 8.0.32. You'll need to contact the maintainers of the original package and get them to fix it, which they will when they feel like it and they'll use another odd disappearing link. I'm sorry for that.

**Comment by lukaszraczylo** [comment]
Hi @skyguy94 thanks for quick reply. You're showing as a maintainer on the package page hence this PR. I've sent them a message using magic-chocolatey-form yesterday but it's literally a blocker for a task I work atm :)

**Comment by skyguy94** [comment]
Yea, I got added so I could fix that package. I'd love to take over, as you can tell, its a pretty trivial job with my version, but original maintainers keep submitting new packages, so I think submitting my own would be rude.

**Comment by lukaszraczylo** [comment]
I wouldn't call it rude but if you've been added as a contributor you should use this power to help actual users :)

**Comment by skyguy94** [comment]
Ok, I pushed an 8.0.29.1 package (to fix the broken one) and submitted an 8.0.32 package. We'll see what the fallout is.

**Comment by lukaszraczylo** [comment]
Sweet! Thank you for your help mate, really appreciate!

**Pull request closed without merging**
