### PR TITLE
Bump mssqlserver-compact3.5 version

### PR DESCRIPTION
**Pull request by csnyder616**
- Bump mssqlserver-compact3.5 to version 3.5.8080.0 (same URL as before)
- Quote extraction path argument to handle spaces in pathnames

### CODE REVIEW

**Comment by skyguy94** [comment]
lul wat? Who is using this?

**Comment by csnyder616** [comment]
Our own new machine provisioning script :-D

**Comment by csnyder616** [comment]
Unless the proper solution is to remove it there... (though fixing a broken package never hurts)

**Comment by skyguy94** [comment]
Oy. We should remove that. I thought the download for this had dissapeared.

**Pull request closed without merging**
